# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 5

[[main]]
  name = "Courses"
  url = "/courses"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 15

[[main]]
  name = "Meet The Team"
  url = "#people"
  weight = 20

[[main]]
  name = "Supporters"
  url = "#supporters"
  weight = 30

[[main]]
  name = "Workshops"
  url = "#talks"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
  name = "<i class='fab fa-patreon'></i>"
  url = "https://patreon.com/schoolnotes"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
