# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 5


[[main]]
  name = "HSC Courses"
  url = "/courses"
  weight = 10
  identifier = "hsc"

[[main]]
  name = "HSC Physics"
  url = "/courses/physics-hsc"
  parent = "hsc"

[[main]]
  name = "HSC Chemistry"
  url = "/courses/chemistry-hsc"
  parent = "hsc"
  
[[main]]
  name = "HSC English Advanced"
  url = "/courses/english-advanced-hsc"
  parent = "hsc"

[[main]]
  name = "HSC Modern History"
  url = "/courses/modern-hsc"
  parent = "hsc"

[[main]]
  name = "HSC Mathematics Standard"
  url = "/courses/mathematics-standard-hsc"
  parent = "hsc"

[[main]]
name = "HSC Biology"
url = "/courses/biology-hsc"
parent = "hsc"  

[[main]]
  name = "HSC PDHPE"
  url = "/courses/pdhpe-hsc"
  parent = "hsc"

[[main]]
  name = "HSC Studies Of Religion"
  url = "/courses/sor-hsc"
  parent = "hsc"  

  
[[main]]
  name = "Preliminary Courses"
  url = "/courses"
  weight = 7
  identifier = "preliminary"

[[main]]
  name = "Preliminary Biology"
  url = "/courses/biology-preliminary"
  parent = "preliminary"

[[main]]
  name = "Preliminary Chemistry"
  url = "/courses/chemistry-prelim"
  parent = "preliminary"

[[main]]
  name = "Preliminary Physics"
  url = "/courses/physics-prelim"
  parent = "preliminary"

[[main]]
  name = "Preliminary Studies Of Religion"
  url = "/courses/sor-prelim"
  parent = "preliminary"

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 15

[[main]]
  name = "Supporters"
  url = "#supporters"
  weight = 50

[[main]]
  name = "Workshops"
  url = "#talks"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
  name = "<i class='fab fa-patreon'></i>"
  url = "https://patreon.com/schoolnotes"
  weight = 80


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
