[build]
  command = "hugo --gc --minify -v -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "https://schoolnotes.intranet.pw"
  to = "https://schoolnotes.xyz"
  status = 301
  force = true
  headers = {X-From = "CSECWebServer"}

[[redirects]]
  from = "https://schoolnotes.intranet.pw/*"
  to = "https://schoolnotes.xyz/:splat"
  status = 301
  force = true
  headers = {X-From = "CSECWebServer"}

[[redirects]]
  from = "http://schoolnotes.intranet.pw"
  to = "https://schoolnotes.xyz"
  status = 301
  force = true
  headers = {X-From = "CSECWebServer"}

[[redirects]]
  from = "http://schoolnotes.intranet.pw/*"
  to = "https://schoolnotes.xyz/:splat"
  status = 301
  force = true
  headers = {X-From = "CSECWebServer"}
  

[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200
  force = true
  headers = {X-From = "CSECWebServer"}

[[redirects]]
  from = "/image-cdn/*"
  to = "https://img-cdn.schoolnotes.xyz/uploads/:splat"
  status = 200
  force = false
  headers = {X-From = "CSECWebServer"}

  [[redirects]]
  from = "/uploads/*"
  to = "https://img-cdn.schoolnotes.xyz/uploads/:splat"
  status = 200
  force = true
  headers = {X-From = "CSECWebServer"}

  [[redirects]]
    from = "/csec-cdn/*"
    to = "https:///csec-cdn.intranet.pw/:splat"
    status = 200
    force = true
    headers = {X-From = "CSECWebServer"}

[security]
[security.csp]
  policy = '''
    default-src 'self';
    connect-src 'self' api.github.com www.netlifystatus.com arc.io tracker.arc.io sentry.arc.io static.arc.io;
    font-src data: arc.io tracker.arc.io sentry.arc.io static.arc.io cdn.jsdelivr.net cdnjs.cloudflare.com fonts.gstatic.com;
    img-src 'self' data: blob: a.tile.openstreetmap.org arc.io tracker.arc.io sentry.arc.io static.arc.io b.tile.openstreetmap.org c.tile.openstreetmap.org cdnjs.cloudflare.com; manifest-src 'self';
    script-src 'self' 'unsafe-inline' 'unsafe-eval' arc.io tracker.arc.io sentry.arc.io static.arc.io buttons.github.io cdn.jsdelivr.net cdnjs.cloudflare.com identity.netlify.com cdn.mathjax.org;
    style-src 'self' 'unsafe-inline' arc.io tracker.arc.io sentry.arc.io static.arc.io cdnjs.cloudflare.com fonts.googleapis.com;
    form-action 'none';
    frame-ancestors 'none';
    object-src 'none';
    base-uri 'none';
    upgrade-insecure-requests;
    report-uri https://schoolnotes.report-uri.com/r/d/csp/enforce
    '''
  report_only = false

[security.permissions]
  policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
  