[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.91.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[dev]
  framework = "hugo"
  command = "hugo server -w --disableFastRender --buildDrafts"
  port = 8888
  targetPort = 1313
  publish = "public"
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    X-From = "NitricAcidWebServer"
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    X-From = "NitricAcidWebServer"


[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
    X-From = "NitricAcidWebServer"

[[redirects]]
  from = "https://schoolnotes.intranet.pw/"
  to = "https://hsc.one/"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "https://schoolnotes.intranet.pw/*"
  to = "https://hsc.one/:splat"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "http://schoolnotes.xyz"
  to = "https://hsc.one"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "https://schoolnotes.xyz/"
  to = "https://hsc.one/"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "/privacy"
  to = "https://pks.ai/privacy"
  status = 301
  force = true
  headers = {X-From = "PrivacyServer"}
  
[[redirects]]
  from = "https://schoolnotes.xyz/*"
  to = "https://hsc.one/:splat"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}
  
[[redirects]]
  from = "http://schoolnotes.xyz"
  to = "https://hsc.one"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "/author/*"
  to = "/authors/:splat"
  status = 200
  force = true
  headers = {X-From = "NitricAcidWebServer"}
[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "/image-cdn/*"
  to = "https://cdn.statically.io/gh/psharma04/image-repo/main/uploads/:splat"
  status = 301
  force = true
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
from = "/uploads/*"
to = "https://cdn.jsdelivr.net/gh/psharma04/image-repo@main/uploads/:splat"
status = 301
force = false
headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
from = "/img-cdn/*"
to = "https://img-cdn.schoolnotes.xyz/:splat"
status = 200
force = false
headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/csec-cdn/*"
  to = "https://csec-cdn.intranet.pw/:splat"
  status = 200
  force = false
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/og-cdn/*"
  to = "https://cdn.statically.io/gh/psharma04/schoolnotes-cdn/625fed21/:splat"
  status = 301
  force = false
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/random-projects/*"
  to = "https://psharma04.github.io/Random-Projects/:splat"
  status = 200
  force = false
  headers = {X-From = "OctocatWebServer"}

[[redirects]]
  from = "/Random-Projects/*"
  to = "https://psharma04.github.io/Random-Projects/:splat"
  status = 200
  force = false
  headers = {X-From = "OctocatWebServer"}

[[redirects]]
  from = "/nesa/*"
  to = "https://educationstandards.nsw.edu.au/wps/wcm/connect/:splat"
  status = 200
  force = false
  headers = {X-From = "HydroniumWebServer"}

[[redirects]]
  from = "/itsfckingraw/*"
  to = "https://raw.githubusercontent.com/psharma04/academic-kickstart/master/:splat"
  status = 200
  force = false
  headers = {X-From = "OctocatWebServer"}

[[redirects]]
  from = "/jsdelivr-proxy/*"
  to = "https://cdn.jsdelivr.net/:splat"
  status = 200
  force = false
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/statically-proxy/*"
  to = "https://cdn.statically.io/:splat"
  status = 301
  force = false
  headers = {X-From = "OctocatWebServer"}

[[redirects]]
  from = "/statically-image-cdn/*"
  to = "https://cdn.statically.io/img/images.schoolnotes.xyz/f=auto/:splat"
  status = 301
  force = false
  headers = {X-From = "OctocatWebServer"}

[[redirects]]
  from = "/rss.xml"
  to = "/index.xml"
  status = 200
  force = false
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/rss/"
  to = "/index.xml"
  status = 200
  force = false
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/rss/*"
  to = "/index.xml"
  status = 200
  force = false
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/ipfs-1/*"
  to = "https://cloudflare-ipfs.com/ipfs/:splat"
  status = 200
  force = false
  headers = {X-From = "InterplanetaryFileSystem"}

[[redirects]]
  from = "/css-repo/*"
  to = "https://cloudflare-ipfs.com/ipfs/QmVu4E6ujjqDViSXRjALprPTosTW5MsW2KNLmD2htVWqHq/fontawesome-5-pro/:splat"
  status = 200
  force = false
  headers = {X-From = "InterplanetaryFileSystem"}

[[redirects]]
  from = "/ipfs/*"
  to = "https://cloudflare-ipfs.com/ipfs/:splat"
  status = 200
  force = false
  headers = {X-From = "InterplanetaryFileSystem"}

[[redirects]]
  from = "/courses/"
  to = "/courses/home/"
  status = 200
  force = true
[[redirects]]
  from = "/courses/index.html"
  to = "/courses/home/"
  status = 200
  force = true

[[redirects]]
  from = "/requests"
  to = "https://tally.so/r/w5dvQ3"
  status = 301
  force = true
  headers = {X-From = "TallyForms"}
  
[[redirects]]
  from = "/patreon/"
  to = "https://patreon.com/hscone/"
  status = 301
  force = true
  headers = {X-From = "Patreon"}
  
[[redirects]]
  from = "/discord/"
  to = "https://discord.gg/wBa9jmbf2e"
  status = 301
  force = true
  headers = {X-From = "Discord"}

