[build]
  command = "hugo mod get -u && hugo --gc --minify -v -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[dev]
  command = "hugo server -v -w --disableFastRender --buildDrafts --noHTTPCache"
  port = 8888
  targetPort = 1313
  publish = "public"
  autoLaunch = true
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    X-From = "NitricAcidWebServer"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    X-From = "NitricAcidWebServer"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
    X-From = "NitricAcidWebServer"

[[redirects]]
  from = "https://schoolnotes.intranet.pw"
  to = "https://schoolnotes.xyz"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "https://schoolnotes.intranet.pw/*"
  to = "https://schoolnotes.xyz/:splat"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "http://schoolnotes.intranet.pw"
  to = "https://schoolnotes.xyz"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "http://schoolnotes.intranet.pw/*"
  to = "https://schoolnotes.xyz/:splat"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "http://courses.schoolnotes.xyz/*"
  to = "https://courses.schoolnotes.xyz/:splat"
  status = 301
  force = true
  headers = {X-From = "NitricAcidWebServer"}


[[redirects]]
  from = "https://courses.schoolnotes.xyz/*"
  to = "https://schoolnotes.xyz/courses/:splat"
  status = 200
  force = true
  headers = {X-From = "NitricAcidWebServer"}


[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200
  force = true
  headers = {X-From = "NitricAcidWebServer"}

[[redirects]]
  from = "/image-cdn/*"
  to = "https://img-cdn.schoolnotes.xyz/uploads/:splat"
  status = 200
  force = false
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
from = "/uploads/*"
to = "https://img-cdn.schoolnotes.xyz/uploads/:splat"
status = 200
force = true
headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
from = "/img-cdn/*"
to = "https://img-cdn.schoolnotes.xyz/:splat"
status = 200
force = true
headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/csec-cdn/*"
  to = "https:///csec-cdn.intranet.pw/:splat"
  status = 200
  force = true
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/random-projects/*"
  to = "https://psharma04.github.io/random-projects/:splat"
  status = 200
  force = true
  headers = {X-From = "HydroniumWebServer"}

[[redirects]]
  from = "/nesa/*"
  to = "https://educationstandards.nsw.edu.au/wps/wcm/connect/:splat"
  status = 200
  force = true
  headers = {X-From = "HydroniumWebServer"}

[[redirects]]
  from = "/itsfckingraw/*"
  to = "https://raw.githubusercontent.com/psharma04/academic-kickstart/master/:splat"
  status = 200
  force = true
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/jsdelivr-proxy/*"
  to = "https://cdn.jsdelivr.net/:splat"
  status = 200
  force = true
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/statically-proxy/*"
  to = "https://cdn.statically.io/:splat"
  status = 200
  force = true
  headers = {X-From = "OctocatWebServer"}

[[redirects]]
  from = "/statically-image-cdn/*"
  to = "https://cdn.statically.io/img/images.schoolnotes.xyz/f=auto/:splat"
  status = 200
  force = true
  headers = {X-From = "OctocatWebServer"}

[[redirects]]
  from = "/rss.xml"
  to = "/index.xml"
  status = 200
  force = true
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/rss/"
  to = "/index.xml"
  status = 200
  force = true
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/rss/*"
  to = "/index.xml"
  status = 200
  force = true
  headers = {X-From = "DeuteriumWebServer"}

[[redirects]]
  from = "/ipfs-1/*"
  to = "https://cloudflare-ipfs.com/ipfs/:splat"
  status = 200
  force = true
  headers = {X-From = "InterplanetaryFileSystem"}
  
[[redirects]]
  from = "/css-repo/*"
  to = "https://cloudflare-ipfs.com/ipfs/QmVu4E6ujjqDViSXRjALprPTosTW5MsW2KNLmD2htVWqHq/fontawesome-5-pro/:splat"
  status = 200
  force = true
  headers = {X-From = "InterplanetaryFileSystem"}